[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "cd backend && python -m pip install -r requirements.txt"
]

[start]
cmd = "cd backend && python -m uvicorn app:app --host 0.0.0.0 --port $PORT" 